// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfjUapeptnR-JkhdP33vr4VHEG7_Ms644',
    appId: '1:946571686802:web:d96056432b5505051d874b',
    messagingSenderId: '946571686802',
    projectId: 'push-noti-b8e96',
    authDomain: 'push-noti-b8e96.firebaseapp.com',
    storageBucket: 'push-noti-b8e96.firebasestorage.app',
    measurementId: 'G-55Y4QJXGSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClQW2-FVNEpzhj3ksfQQxwHvicMmww22c',
    appId: '1:946571686802:android:e2ee444c1d23a4611d874b',
    messagingSenderId: '946571686802',
    projectId: 'push-noti-b8e96',
    storageBucket: 'push-noti-b8e96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Zm3ZrIOToDmamjgFRCI6EEojfyHFWLI',
    appId: '1:946571686802:ios:e7711f2fd0942b1f1d874b',
    messagingSenderId: '946571686802',
    projectId: 'push-noti-b8e96',
    storageBucket: 'push-noti-b8e96.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Zm3ZrIOToDmamjgFRCI6EEojfyHFWLI',
    appId: '1:946571686802:ios:e7711f2fd0942b1f1d874b',
    messagingSenderId: '946571686802',
    projectId: 'push-noti-b8e96',
    storageBucket: 'push-noti-b8e96.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfjUapeptnR-JkhdP33vr4VHEG7_Ms644',
    appId: '1:946571686802:web:4a5df735ded13d3a1d874b',
    messagingSenderId: '946571686802',
    projectId: 'push-noti-b8e96',
    authDomain: 'push-noti-b8e96.firebaseapp.com',
    storageBucket: 'push-noti-b8e96.firebasestorage.app',
    measurementId: 'G-M7MHYWQDR6',
  );
}
